spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://mysql-1bd69c46-capstone2.g.aivencloud.com:25590/devclass?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: avnadmin
    password: AVNS_Ozi4pud2pUgpPbOzJ9V
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8082